name: netindo_shop
description: Netindo Shop

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_svg: ^0.18.0
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  curved_navigation_bar: ^0.3.0
  sqflite: ^1.3.1+1
  provider: ^4.3.2+2
  http: ^0.12.1
  intl: ^0.15.7
  device_info: ^0.4.1+5
  onesignal_flutter: ^2.2.0
  liquid_pull_to_refresh: ^2.0.0
  flushbar: ^1.10.4
  image_picker: ^0.6.7+12
  flutter_cupertino_date_picker:
  flutter_rating_bar:
  shared_preferences: ^0.5.12+4
  country_code_picker: ^1.2.2
  animated_widgets: ^1.0.6
  scrollable_positioned_list: ^0.1.8
  cached_network_image: ^2.4.1
  uni_links: any
  geolocator: ^5.3.1
  flutter_sticky_header: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  shimmer: ^1.1.2
#  theme_provider: ^0.4.0+1
  percent_indicator: ^2.1.9
#  flutter_login_facebook: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/img/
    - img/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat.ttf

    - family:  Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Light.ttf
    - family:  EcommerceAppUI
      fonts:
        - asset: fonts/EcommerceAppUI.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900