name: miski_shop
description: Miski Shop


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  touch_ripple_effect: ^2.1.3
  carousel_slider: ^2.2.1
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_staggered_grid_view: ^0.3.0
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  sqflite: ^1.3.1+1
  provider: ^4.3.2+4
  http: ^0.12.1
  intl: ^0.15.7
  onesignal_flutter: ^2.2.0
  liquid_pull_to_refresh: ^2.0.0
  flushbar: ^1.10.4
  image_picker: ^0.6.7+12
  flutter_cupertino_date_picker:
  smooth_star_rating: 1.1.1
  shared_preferences: ^0.5.12+4
  animated_widgets: ^1.0.6
  scrollable_positioned_list: ^0.1.8
  cached_network_image: ^2.4.1
  geolocator: ^5.3.1
  flutter_sticky_header: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  shimmer: ^1.1.2
  flutter_screen_scaler: ^2.0.0
  flutter_icons: ^1.1.0
  google_fonts: ^1.1.0
  google_maps_flutter: ^1.2.0
  getwidget: ^2.0.3
  flutter_html: ^0.11.1
  pretty_qr_code: ^1.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
    - assets/
  #    - img/
  fonts:
    - family:  EcommerceAppUI
      fonts:
        - asset: fonts/EcommerceAppUI.ttf
